import sublime, sublime_plugin

class German(sublime_plugin.TextCommand):
	def run(self, edit):
		self.search_replace(edit, "oe", "ö")
		self.search_replace(edit, "Oe", "Ö")
		self.search_replace(edit, "ae", "ä")
		self.search_replace(edit, "Ae", "Ä")
		self.search_replace(edit, "ue", "ü")
		self.search_replace(edit, "Ue", "Ü")

		# Correct some of the ones we didn't exclude.
		self.search_replace(edit, "Neü", "Neue")
		self.search_replace(edit, "neü", "neue")
		self.search_replace(edit, "eventüll", "eventuell")
		self.search_replace(edit, "Eventüll", "Eventuell")
		self.search_replace(edit, "söben", "soeben")
		self.search_replace(edit, "Söben", "Soeben")
		self.search_replace(edit, "aktüll", "aktuell")
		self.search_replace(edit, "Aktüll", "Aktuell")
		self.search_replace(edit, "steür", "steuer")
		self.search_replace(edit, "Steür", "Steuer")
		self.search_replace(edit, "Blütooth", "Bluetooth")
		self.search_replace(edit, "blütooth", "bluetooth")
		self.search_replace(edit, "daürt", "dauert")
		self.search_replace(edit, "Daürt", "Dauert")
		self.search_replace(edit, "baün", "bauen")
		self.search_replace(edit, "Baün", "Bauen")
		self.search_replace(edit, "schaün", "schauen")
		self.search_replace(edit, "Schaün", "Schauen")
		self.search_replace(edit, "daürhaft", "dauerhaft")
		self.search_replace(edit, "Daürhaft", "Dauerhaft")
		self.search_replace(edit, "individüll", "individuell")
		self.search_replace(edit, "Individüll", "Individuell")
		self.search_replace(edit, "vertraün", "vertrauen")
		self.search_replace(edit, "Vertraün", "Vertrauen")
		self.search_replace(edit, "Qüsadilla", "Quesadilla")
		self.search_replace(edit, "qüsadilla", "quesadilla")
		self.search_replace(edit, "Raushaün", "Raushauen")
		self.search_replace(edit, "raushaün", "raushauen")
		self.search_replace(edit, "virtüll", "virtuell")
		self.search_replace(edit, "Virtüll", "Virtuell")
		self.search_replace(edit, "qülle", "quelle")
		self.search_replace(edit, "Qülle", "Quelle")
		self.search_replace(edit, "Dü ", "Due ")
		self.search_replace(edit, "dü ", "due ")
		self.search_replace(edit, "Daür", "Dauer")
		self.search_replace(edit, "daür", "dauer")
		self.search_replace(edit, "Sexüll", "Sexuell")
		self.search_replace(edit, "sexüll", "sexuell")
		self.search_replace(edit, "Kaü", "Kaue")
		self.search_replace(edit, "kaü", "kaue")
		self.search_replace(edit, "Qüstion", "Question")
		self.search_replace(edit, "qüstion", "question")
		self.search_replace(edit, "flüntly", "fluently")
		self.search_replace(edit, "Flüntly", "Fluently")
		self.search_replace(edit, "fraün", "frauen")
		self.search_replace(edit, "Fraün", "Frauen")
		self.search_replace(edit, "Blaün", "Blauen")
		self.search_replace(edit, "blaün", "blauen")
		self.search_replace(edit, "qüen", "queen")
		self.search_replace(edit, "Qüen", "Queen")

		# ß cases.
		self.search_replace(edit, "gross", "groß")
		self.search_replace(edit, "Gross", "Groß")
		self.search_replace(edit, "strasse", "straße")
		self.search_replace(edit, "Strasse", "Straße")
		self.search_replace(edit, "weiss", "weiß")
		self.search_replace(edit, "Weiss", "Weiß")
		self.search_replace(edit, "grüsse", "grüße")
		self.search_replace(edit, "Grüsse", "Grüße")
		self.search_replace(edit, "gröss", "größ")
		self.search_replace(edit, "Gröss", "Größ")
		self.search_replace(edit, "Schoss", "Schoß")

	def search_replace(self, edit, search, replace):
		regions = self.view.find_all(search)

		for region in reversed(regions):
			self.view.replace(edit, region, replace)